apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Staged L3 Entry Check
on:
  workflow_dispatch:
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - L4-scan-job
    - name: Stage
      jobs:
        - independent-job
    - name: Stage1
      jobs:
        - post-scan-job
jobs:
  independent-job:
    needs:
      - L4-scan-job
    steps:
      - run: echo "independent-job running"
        uses: docker://golang:1.20.3-alpine3.17
        name: Run step
        shell: sh
  post-scan-job:
    needs: independent-job
    steps:
      - run: echo "post-scan-job running"
        uses: docker://alpine:3.18
        name: Run step
  L4-scan-job:
    uses: .cloudbees/workflows/auto-pe-l4-continue-on-error.yaml@main
