apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Staged L3 Entry Check
on:
  workflow_dispatch:
metadata:
  stages/v1alpha1:
    - name: scan
      jobs:
        - scan-job
    - name: Stage
      jobs:
        - independent-job
    - name: Stage1
      jobs:
        - post-scan-job
jobs:
  scan-job:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: check out
      - uses: cloudbees-io/gosec-plugin@v1
        name: gosec
  independent-job:
    needs: scan-job
    steps:
      - run: echo "independent-job running"
        uses: docker://golang:1.20.3-alpine3.17
        name: Run step
        shell: sh
  post-scan-job:
    needs:
      - independent-job
    steps:
      - run: echo "post-scan-job running"
        uses: docker://alpine:3.18
        name: Run step
